# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: J. David Beltrán
email: jobeltranl@unal.edu.co
description: 
#Powered by <a href="http://jekyllthemes.org/themes/svm-ngvb/">Steve's NGVB theme.</a>
>- # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: alexaleg
github_username:  jdavidbel
orcid_username: J. David Beltrán
#linkedin_username: aleguizamonr
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
#  - jekyll-relative-links

analytics:
    provider: google
    statcounter:
        sc_project  :
        sc_security :
        sc_invisible: 1
        sc_text     : 2
    google:
        tracking_id: 'UA-159814879-2'
    getclicky:
      site_id:
    mixpanel:
        token: ''
    piwik:
        baseURL: '' # Piwik installation address (without protocol)
        idsite: ''  # the id of the site on Piwik


include: ['_pages']
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
